### ISSUE TITLE
Ability to define functions inside tests

### ISSUE THREAD

**Issue by unode** [wbsch/bash_tap#1]
Hello there,

```
#!/usr/bin/env bash

source bash_tap.sh

function nothinghere {
    echo "Hello world"
}
```

This fails with an `eval: line 43: syntax error: unexpected end of file`.

Is there any way to define functions inside the test?
I'd like to avoid some of the code duplication visible in this [`example of misuse`](https://github.com/Unode/firefox_decrypt/tree/master/tests) :smile: 

Cheers!

**Comment by wbsch** [comment]
Hi Unode,

you didn't follow rule 1 of bash_tap.sh - "No multi-line Bash constructs".

Defining functions on multiple lines is fine in a helper script which you then include in your tests, so you could just add that function to your bash_tap_fd.sh helper.

If you really insist on defining functions in your tests, you'll have to do it like this:

```
$ cat foo.t 
#!/usr/bin/env bash
source bash_tap.sh

function nothinghere { echo "Hello world"; }
nothinghere | grep Hello
nothinghere | grep hcsvntdrcns

$ bash foo.t 
1..1
# $ function nothinghere { echo "Hello world"; }
# $ nothinghere | grep Hello
# >>> Hello world
# $ nothinghere | grep hcsvntdrcns
not ok 1 - nothinghere | grep hcsvntdrcns
```

And by the way, nice work taking this little abomination of a Bash script to places where it has no right to be! :)

**Comment by unode** [comment]
Thanks for the clarification.
I'll use the `bash_tap_fd.sh` file for any future code reuse.

If only all "little abominations" out there managed to get the job done, the world... ;)
